language: ruby
rvm:
 - "2.2.0"
# uncomment this line if your project needs to run something other than `rake`:
before_script:
  - npm install karma
script:
  - bundle exec rspec spec
  - karma start --single-run
bundler_args: --without darwin
